name:                ImageCompressor
dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  imageCompressor-exe:
    main:                main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImageCompressor
